spring:
  application:
    name: "football_manager"
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    username: root
    password: 12345678
    url: jdbc:mysql://localhost:3306/football_manager
    driver-class-name: com.mysql.jdbc.Driver
server:
  port: 9000